# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortemplate',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.MonitorNotifyPolicy', verbose_name='\u544a\u8b66\u7b56\u7565'),
        ),
    ]
