# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20180404_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitortemplate',
            name='policy',
        ),
        migrations.AddField(
            model_name='monitortemplate',
            name='policy',
            field=models.ManyToManyField(blank=True, null=True, to='master.MonitorNotifyPolicy', verbose_name='\u544a\u8b66\u7b56\u7565'),
        ),
    ]
