# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20180409_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u540d\u79f0')),
                ('value', models.CharField(max_length=255, verbose_name='\u952e\u503c')),
            ],
        ),
        migrations.RemoveField(
            model_name='monitortemplate',
            name='items',
        ),
        migrations.AddField(
            model_name='monitortemplate',
            name='items',
            field=models.ManyToManyField(to='master.MonitorItem', verbose_name='\u76d1\u63a7\u9879'),
        ),
    ]
